CREATE or REPLACE SCHEMA MANAGE_DB.file_formats;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.CSV_FILE
TYPE = 'CSV'
FIELD_DELIMITER = ','             
SKIP_HEADER = 1                   
FIELD_OPTIONALLY_ENCLOSED_BY = '"' ;
